import datetime
# print(dir(datetime))
# print(help(datetime.date))
gvr = datetime.date(1956, 1, 31)
print(gvr)
print(gvr.year)
print(gvr.month)
print(gvr.day)
print()
mill = datetime.date(2000, 1, 1)
dt = datetime.timedelta(100)
print(mill + dt)
print()
# Day-name, Month-name Day-#, Year
print(gvr.strftime("%A,%B %d, %Y"))
message = "GVR was born on {:%A,%B %d, %Y}"
print(message.format(gvr))
print()
launch_date = datetime.date(2017, 3, 30)
launch_time = datetime.time(22, 27, 0)
launch_datetime = datetime.datetime(2017, 3, 30, 22, 27, 0)
print(launch_date)
print(launch_date.year, launch_date.month, launch_date.day)
print(launch_time)
print(launch_time.hour, launch_time.minute, launch_time.second)
print(launch_datetime)
print(launch_datetime.year, launch_datetime.month, launch_datetime.day,launch_datetime.hour, launch_datetime.minute, launch_datetime.second)
print()
now = datetime.datetime.today()
print(now)
print(now.microsecond)
print()
moonlanding = "7/20/1969"
moon_landing_datetime = datetime.datetime.strptime(moonlanding, "%m/%d/%Y")
print(moon_landing_datetime)
print(type(moon_landing_datetime))