# Blean values: True, False
print(True)
print(False)
print()
a = 3
b = 5
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print()
print(type(True))
print(type(False))
print()
print(bool(28))
print(bool(-2.71828))
print(bool(0))
print()
print(bool("Turing"))
print(bool(" "))
print(bool(""))
print()
print(str(True))
print(str(False))
print(int(True))
print(int(False))
print()
print(5 + True)
print(10 * False)