# Integers 1 - 10
odds = set([1, 3, 5, 7, 9])
evens = set([2, 4, 6, 8, 10])
primes = set([2, 3, 5, 7])
composites = set([4, 6, 8, 9, 10])
print(odds.union(evens))
print(evens.union(odds))
print(odds)
print(evens)
print(odds.intersection(primes))
print(primes.intersection(evens))
print(evens.intersection(odds))
print(primes.union(composites))
print(2 in primes)
print(6 in odds)
print(9 not in evens)